[package]
name = "abc241"
version = "0.1.0"
edition = "2018"

# dependencies added to new project
[dependencies]
proconio = { version = "0.4.0", features = ["derive"] }
itertools = "0.10.1"

[profile.release]
lto = true
panic = 'abort'
